[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://bprowyyzwtedszibbvon.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_-Le3fA7ZrIAC0go2CwifHA_XT3x7_pK"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200